# file ./softwareengineering/.github/workflow/deploy.yml

name: 'Deploy master branch'

on:
  push:
    branches:
      - master

jobs:
  deploy_website:
    name: 'deploy website'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: 'Installing dependencies'
      run: 'npm ci'
    - name: 'Deploying to now'
      uses: artemis-tech/zeit-now-cli@v1
      env:
          ZEIT_TOKEN: ${{ secrets.TOKEN }}
      with:
          args:  --prod