# file ./softwareengineering/.github/workflow/deploy.yml

name: 'Deploy master branch'

on:
  push:
    branches:
      - master

jobs:
  Setup site:
    name: 'Install dependencies'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: 'Installing dependencies'
      run: 'npm ci'
  Deploy site:
    name: 'Deploy site'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: amondnet/now-deployment@v2
      with: 
        zeit-token: ${{ secrets.TOKEN }}
        now-org-id: ${{ secrets.ACCOUNT_ID }}
        now-project-id: ${{ secrets.PROJECT_ID}}
        working-directory: ./
        now-args: '--prod' #Optional